### ISSUE TITLE
Dynamic named data

### ISSUE THREAD

**Issue by tuner** [genome-spy/genome-spy#131]
# Intro

GenomeSpy has rudimentary support for [named data source](https://vega.github.io/vega-lite/docs/data.html#named). It's used in the Playground app to access data "uploaded" by the user. However, although it seems to support dynamic data updates, it is not exposed through the public GenomeSpy API.

https://github.com/genome-spy/genome-spy/blob/16b88c31fcdb8bfb2e679defd0f1a162330a2ead/packages/core/src/data/sources/namedSource.js#L40

Currently, when the user updates the data in Playground, the whole visualization is rebuilt:

https://github.com/genome-spy/genome-spy/blob/16b88c31fcdb8bfb2e679defd0f1a162330a2ead/packages/playground/src/index.js#L144

Implementing dynamic named data is the first step in implementing https://github.com/genome-spy/genome-spy/issues/111.

# Steps

- [x] Refactor `namedDataProvider` in `EmbedOptions`. Data provider should be able to trigger an update.
- [x] Design and implement a public API for looking up a named-data handle and pushing new data.
- [ ] Use the API in Playground to dynamically update the data (instead of rebuilding the whole vis)
- [x] Add some fancy examples to [embed-examples](https://github.com/genome-spy/genome-spy/tree/master/packages/embed-examples), e.g., periodically update the dataset
- [x] Write documentation

# Additional considerations

The initial version of the API will update the whole dataset behind the named data source. At a later time, we could implement tiled data with multiple resolutions. See: https://github.com/genome-spy/genome-spy/issues/109.

Support for fine-grained [change](https://github.com/vega/vega-view#view_change), insert, or remove operations is not feasible, as GenomeSpy dataflow is optimized for large continuous blocks of data. And moreover, surgical modification of GPU buffers would lead to bad performance. Also, because the dataset will be just replaced, implementing fancy transitions for the data items is impossible. Quantitative scale domains (on `x` and `y` channels, maybe `color` and `size` at a later time) can be adjusted with smooth animation, however.

**Comment by tuner** [comment]
@grsr, There's now an example in the `dynamic-named-data` branch. Could you have a look at it and give it a try?

![fancy stuff](https://user-images.githubusercontent.com/399972/195048854-05824217-65f9-4b8b-8d90-04dfa4c1ea43.gif)

https://github.com/genome-spy/genome-spy/blob/dynamic-named-data/packages/embed-examples/src/dynamicNamedData.js

You can launch the examples with:
```sh
% npm -w @genome-spy/embed-examples run dev
```

There are still some issues to be solved at some point. For instance, it's best to specify domains for categorical fields explicitly. Some strange things happen if data domain changes (it's a bug somewhere).

**Comment by grsr** [comment]
Hi Kari - Thanks for this, looks great! I'll definitely try to give it a
shot soon.

Apologies I haven't been in touch recently, I keep getting distracted by
other far less-interesting work!, Ee are making good progress on the full
implementation of the plots, and have figured out how to get named data
working and it's making for a nice clean integration with the app.

We are keen to collaborate a bit more on the codebase, but at the moment we
are under the gun to get an initial release out this year, so I'm not sure
how much we will be able to push back your way in the short term I'm
afraid. One thing we have had to do is implement a variation on the 'link'
mark to allow us to control the height of the arcs according to the support
for structural variants. Once we get an implementation we're happy with
we'll send it your way to see if you think it might be useful for others.

All the best,

Graham

**Comment by tuner** [comment]
Okay! In that case, I'll probably merge the branch soon and continue with #111 once I have some time for it.

**Comment by grsr** [comment]
Hey - Actually, I forgot we have a requirement to support highlighting an
SV based on the user clicking elsewhere in the app. I will have a go at
implementing this with dynamic named data and let you know how I get on!
