### ISSUE TITLE
Y axis doesn't update the scale while loading dynamic data

### ISSUE THREAD

**Issue by tuner** [genome-spy/genome-spy#183]
### Discussed in https://github.com/genome-spy/genome-spy/discussions/182

<div type='discussions-op-text'>

<sup>Originally posted by **EddyGenome** August 22, 2023</sup>
Hello,

I'm using the "updateNamedData" function to push dynamic data into same chart but with multiple layers with 3 different data sources, but the Y scale doesn't refresh Y coordinates with "merged" scale between data sources, can I force the rendering after each data pushed into namedData?

Thanks</div>

**Comment by tuner** [comment]
@EddyGenome, there definitely seem to be some issues when the scale domain isn't specified explicitly. I'll figure this out but it may take a few days.

**Comment by EddyGenome** [comment]
@tuner Thank you for the support!
