### ISSUE TITLE
Make a React example and/or component

### ISSUE THREAD

**Issue by tuner** [genome-spy/genome-spy#226]
Related to #225 

This could be useful for new users. I just have minimal React expertise.

Alternatively, a Web Component could be provided, as they should be mostly compatible with React.

**Comment by trentfridey** [comment]
Hi - I would like to see this accomplished. I have plenty of experience with React. I can help if you would outline what you had in mind for the end product.

**Comment by tuner** [comment]
Hi @trentfridey,

I'd like to better understand the problems a React component would solve. For instance, what are the challenges in using the `embed` API in a React application? Are they related to developer experience, compatibility with vDOM, lifecycle, state management, events, or something else?

I'm using [Web Component](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) to embed interactive visualizations into the documentation [conveniently](https://github.com/genome-spy/genome-spy/tree/master/packages/doc-embed). I could imagine that something similar would be useful in React apps.

Perhaps these other projects could provide some thoughts and ideas:
- https://github.com/gosling-lang/gosling-react-example/
- https://github.com/vega/react-vega

I think that at minimum, a React component should provide a super-easy way to add a visualization to React app and provide an access to GenomeSpy's [API](https://github.com/genome-spy/genome-spy/blob/18c7d678a24129401227f1e8a6fb271afb5a8661/packages/core/src/types/embedApi.d.ts#L48). Something like this:

```jsx
<GenomeSpy spec={this.state.spec} />
```

**Comment by tuner** [comment]
I forgot to emphasize that pull requests are welcome!

I think the component should be placed in a new package in the monorepo, e.g., `@genome-spy/react-component`. The core package should have no react dependencies.

**Comment by trentfridey** [comment]
Thanks, I will see what I can do.

**Comment by zhangzhen** [comment]
> Hi @trentfridey,
> 
> I'd like to better understand the problems a React component would solve. For instance, what are the challenges in using the `embed` API in a React application? Are they related to developer experience, compatibility with vDOM, lifecycle, state management, events, or something else?
> 
> I'm using [Web Component](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) to embed interactive visualizations into the documentation [conveniently](https://github.com/genome-spy/genome-spy/tree/master/packages/doc-embed). I could imagine that something similar would be useful in React apps.
> 
> Perhaps these other projects could provide some thoughts and ideas:
> 
> * https://github.com/gosling-lang/gosling-react-example/
> * https://github.com/vega/react-vega
> * https://github.com/vega/svelte-vega/tree/main/packages/svelte-vega
> 
> And here is perhaps the simplest possible Web Component implementation: #90
> 
> I think that at minimum, a React component should provide a super-easy way to add a visualization to React app and provide an access to GenomeSpy's [API](https://github.com/genome-spy/genome-spy/blob/18c7d678a24129401227f1e8a6fb271afb5a8661/packages/core/src/types/embedApi.d.ts#L48). Something like this:
> 
> ```js
> <GenomeSpy spec={this.state.spec} />
> ```
> 
> ## Updating data
> It seems that both `react-vega` and `svelte-vega` input the spec and data as separate attributes. Of course, all data can still be embedded in the spec. However, having a separate attribute for data allows for updating the data dynamically without rebuilding the whole visualization.

Recently i've switched from React to Svelte. Which is the integration of genomespy into a web app more appropriate via web component or Svelte component?
