### ISSUE TITLE
Importing NPM lib return a TS2307: Cannot find module @genome-spy/core or its corresponding type declarations.

### ISSUE THREAD

**Issue by EddyGenome** [genome-spy/genome-spy#260]
Using import in Angular from NPM generate this error and I can't use the "embed" from core  or app libs.

I'm using Angular v17, Node v18

TS2307: Cannot find module @genome-spy/core or its corresponding type declarations.
There are types at
/@genome-spy/core/dist/src/index.d.ts
, but this result could not be resolved under your current moduleResolution setting. Consider updating to node16, nodenext, or bundler

**Comment by tuner** [comment]
Thanks for the report! Could you provide me with a super-simple reproducer that would allow me to experiment with the problem and ensure that the fix (whatever it will be) really fixes the problem?

I have had some challenges getting the types in GenomeSpy monorepo and the generated .d.ts files in published packages to work properly. Apparently, there's still some work to do. 🤨

**Comment by EddyGenome** [comment]
Solved using lib in Angular by changing these options:

 **tsconfig.json**

"compilerOptions" : {
...
    "moduleResolution": "bundler",
    "module": "es2015",
...
}

**Comment by tuner** [comment]
> Solved using lib in Angular by changing these options:

Ah, good!

Module types (cjs vs esm) and resolutions are quite a mess in the JavaScript ecosystem.
