### ISSUE TITLE
Implement a minimum width/size for strokes/lines in the picking buffer

### ISSUE THREAD

**Issue by tuner** [genome-spy/genome-spy#84]
Hovering rules or strokes that are just 1px wide is currently quite difficult. See: https://genomespy.app/examples/?spec=SV/sv.json

A minimum width of, say, 2px could be enforced in the shaders when rendering to the picking buffer.

**Comment by mattjvincent** [comment]
Is it possible to add the ability to highlight the hovered component?

**Comment by tuner** [comment]
> Is it possible to add the ability to highlight the hovered component?

That's something I'd like to implement at some point. It would be especially useful in the visualization I linked above.
